@ECHO OFF
REM
REM Called by PluginManager by way of CRDT_manifest.json. 
REM

IF "%SPRK_COMMANDS_DIR%" == "" (
    SET SPRK_COMMANDS_DIR=%~dp0
)

SET SOURCE_PACKAGE_FOLDER=%~s1
SET TARGET_PACKAGE_FOLDER=%~s2
SET FILE_PATH_PLUGIN_INSTALLER_RESOURCES=%~s3
SET FILE_PATH_CODE_SIGN_CERTIFICATE=%~s4
SET CODE_SIGN_CERTIFICATE_PASSWORD=%5
SET URL_TIME_STAMP_SERVER=%6
SET INJECT_DEBUG_FILE=%7

PUSHD "%SPRK_COMMANDS_DIR%.."
SET PROJECT_ROOT_DIR=%cd%\
POPD

IF "%PROCESSOR_ARCHITECTURE%" == "ARM64" GOTO UNSUPPORTED_ARM

CALL "%SPRK_COMMANDS_DIR%adjustVersionDependencies.bat" NESTED

GOTO DONE

:UNSUPPORTED_ARM
ECHO Windows on ARM is currently unsupported
GOTO DONE

:DONE